[package]
name = "rs-queue-processor"
version = "0.1.0"
authors = ["Jack Wright <jack.wright@nike.com>"]
edition = "2018"

[dependencies]
tokio = "0.1"
rusoto_core = "0.36"
rusoto_sqs = "0.36"
rusoto_credential = "0.15"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
futures = "0.1"
log = "0.4"
clap = "2.32"

[dev-dependencies]
testcontainers = { git = "https://github.com/testcontainers/testcontainers-rs.git" }
